In [97]:
import pandas as pd
import numpy as np

In [98]:
df=pd.read_csv('../data/books.csv',on_bad_lines='skip')

In [99]:
df.shape

(11123, 12)

In [100]:
df.head(10)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic
5,9,"Unauthorized Harry Potter Book Seven News: ""Ha...",W. Frederick Zimmerman,3.74,0976540606,9780976540601,en-US,152,19,1,4/26/2005,Nimble Books
6,10,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,0439827604,9780439827607,eng,3342,28242,808,9/12/2005,Scholastic
7,12,The Ultimate Hitchhiker's Guide: Five Complete...,Douglas Adams,4.38,0517226952,9780517226957,eng,815,3628,254,11/1/2005,Gramercy Books
8,13,The Ultimate Hitchhiker's Guide to the Galaxy ...,Douglas Adams,4.38,0345453743,9780345453747,eng,815,249558,4080,4/30/2002,Del Rey Books
9,14,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams,4.22,1400052920,9781400052929,eng,215,4930,460,8/3/2004,Crown

In [101]:
df.tail(5)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
11118,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,1560254416,9781560254416,eng,512,156,20,12/21/2004,Da Capo Press
11119,45633,You Bright and Risen Angels,William T. Vollmann,4.08,0140110879,9780140110876,eng,635,783,56,12/1/1988,Penguin Books
11120,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,0140131965,9780140131963,eng,415,820,95,8/1/1993,Penguin Books
11121,45639,Poor People,William T. Vollmann,3.72,0060878827,9780060878825,eng,434,769,139,2/27/2007,Ecco
11122,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,8497646983,9788497646987,spa,272,113,12,5/28/2006,Edimat Libros

In [102]:
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', '  num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='str')

In [103]:
df.dtypes

bookID                  int64
title                     str
authors                   str
average_rating        float64
isbn                      str
isbn13                  int64
language_code             str
  num_pages             int64
ratings_count           int64
text_reviews_count      int64
publication_date          str
publisher                 str
dtype: object

In [104]:
df.describe()

,bookID,average_rating,isbn13,num_pages,ratings_count,text_reviews_count
count,11123.000000,11123.000000,1.112300e+04,11123.000000,1.112300e+04,11123.000000
mean,21310.856963,3.934075,9.759880e+12,336.405556,1.794285e+04,542.048099
std,13094.727252,0.350485,4.429758e+11,241.152626,1.124992e+05,2576.619589
min,1.000000,0.000000,8.987060e+09,0.000000,0.000000e+00,0.000000
25%,10277.500000,3.770000,9.780345e+12,192.000000,1.040000e+02,9.000000
50%,20287.000000,3.960000,9.780582e+12,299.000000,7.450000e+02,47.000000
75%,32104.500000,4.140000,9.780872e+12,416.000000,5.000500e+03,238.000000
max,45641.000000,5.000000,9.790008e+12,6576.000000,4.597666e+06,94265.000000

In [105]:
df=df.drop(['isbn','isbn13'],axis = 1)

The ("  num_pages") column has hidden spaces in the front - it will cause the error when we try to use that
To Overcome this problem we can clean all the column names once - remove spaces and same style for all

In [106]:
df.columns=df.columns.str.strip().str.title()

we checked for empty cells and found nothing. but the real missing data is hiding as fake numbers - books with 0 pages and books with 0 ratings, we handle those separately

In [107]:
df.isna().sum()

Bookid                0
Title                 0
Authors               0
Average_Rating        0
Language_Code         0
Num_Pages             0
Ratings_Count         0
Text_Reviews_Count    0
Publication_Date      0
Publisher             0
dtype: int64

In [108]:
df = df.drop_duplicates(subset=['Bookid']).reset_index(drop=True)
df.shape

(11123, 10)

The Publication date is stored as str(Text) like 9/16/2006, so we take the last 4 characters to get the year. then convert it to a number and calculate the age of the book = 2026 − publication year

In [109]:
df['Publication_Year'] = df['Publication_Date'].str[-4:]
df['Publication_Year'] = pd.to_numeric(df['Publication_Year'])

df['Age']=2026-df['Publication_Year']

In [110]:
df['Publication_Year'].min(),df['Publication_Year'].max()

(np.int64(1900), np.int64(2020))

the language codes are messy (eng, en-us, en-gb all mean English), so a small function cleans them: 
first it checks the keys — if the word is present,the right value is translated and given back. 
then it checks the values — if the word is present, return it as it is.
or else mark it as Others.

In [111]:
language = {'eng':'English','en-us':'English','en-gb':'English','en-ca':'English',
            'fre':'French','spa':'Spanish','ger':'German','jpn':'Japanese'}

def clean_language(key):
    if key in language:
        return language[key]
    if key in language.values():
        return key
    return 'Others'

df['Language_Code']=df['Language_Code'].str.lower().apply(clean_language)
df['Language_Code'].value_counts()

Language_Code
English     10537
Spanish       218
French        144
German         99
Others         79
Japanese       46
Name: count, dtype: int64

Books with 0 pages and Books with 0 ratings.
A book cannot have 0 pages, so those are data errors → we drop them.
The 0 rating books are real (real books, just nobody rated them) → we keep them here but leave them out later when training the model because their rating is not real.

In [112]:
print("Books with 0 ratings:", (df['Ratings_Count'] == 0).sum())
print("Books with 0 pages:", (df['Num_Pages'] == 0).sum())

Books with 0 ratings: 80
Books with 0 pages: 76

In [113]:
df =df[(df['Num_Pages'] > 0) & (df['Ratings_Count'] > 0)].reset_index(drop=True)
df.shape

(10968, 12)

In [114]:
df.to_csv('../data/books_clean_v2.csv', index=False)